---
title: Tekdycaml (anyone-developer)
timezone: Asia/Shanghai
email: zhang_nan_163@163.com
description: 'Writing something useful. Not really true. Not really false. Leave something eternality.'
baseurl: ''
url: 
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
- jekyll-feed
style: hacker
header_pages:
- home.md
- gallery.md
- feedback.md
- whoami.md
show_drafts: true
footer: Walking in the dark to serve the light.
